name: Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to server
      env:
        HOSTINGER_HOST: ${{ secrets.hostinger_host }}
        HOSTINGER_USER: ${{ secrets.hostinger_user }}
        HOSTINGER_PASSWORD: ${{ secrets.hostinger_password }}
      run: |
        sshpass -p "$HOSTINGER_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $HOSTINGER_USER@$HOSTINGER_HOST << 'EOF'
          cd projects/VPS-File-Host 
          git pull
          pm2 restart file-host
        EOF