name: Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to server
      env:
        HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
        HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
        HOSTINGER_PASSWORD: ${{ secrets.HOSTINGER_PASSWORD }}
      run: |
        sshpass -p "$HOSTINGER_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $HOSTINGER_USER@$HOSTINGER_HOST '
          cd projects &&
          cd VPS-File-Host &&
          git pull &&
          npm install &&
          pm2 restart file-host
        '